### ISSUE TITLE
Opossum parameters for single-end reads?

### ISSUE THREAD

**Issue by messersc** [BSGOxford/Opossum#7]
Hi,

I was wondering which Opossum parameters I should set for single-end reads.

I think I need to set `--ProperlyPaired ` to false, because it looks like I'm not getting any reads otherwise.

Any other things I should take into account? What would be the recommended way to run opossum and platypus on single-end RNA-seq data?

Thanks,
Clemens

**Comment by ibwoo** [comment]
I'm also interested in an answer to this. 

Additionally, though GitHub has tracked only a single release dating back to Dec 2016, you have probably noticed in the readme file the following update from 2017:

> 0.2
> 
> Released on February 23, 2017. Updated dependency to Pysam v0.10.0. Opossum now supports unpaired data and filters out unmapped reads. Bug fixes.

So I'd say to check that you've downloaded the latest code, which may not be the 'latest release'.

**Comment by messersc** [comment]
Hi,

I totally missed that. I was on https://github.com/BSGOxford/Opossum/commit/de259b45a35cd7d4c01dbb40d48d16c9118d76c4, which is newer than the 0.2 commit though.

Guess I will need to revisit my analysis.

Thanks,
Clemens

**Comment by laura-oikkonen** [comment]
Hello and apologies for the late reply. I have moved on to another field and unfortunately don't have time to maintain the Opossum code any more. Opossum indeed supports single-end reads, please use the latest code which is fe8f72e committed on 10 Apr 2018.
Best regards,
Laura

**Comment by Udaykage** [comment]
**Hi Guys
I am using opossum for pre-processing my rna-seq bam files for variant calling and I got some errors as below, could you please help me with what the error means and how to fix it.
-----------------------------------------------------------------------------
ERROR:
**_[E::hts_idx_push] Region 536872898..536872913 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
Traceback (most recent call last):
  File "/apps/opossum/0.2/Opossum.py", line 2074, in <module>
    main()
  File "/apps/opossum/0.2/Opossum.py", line 482, in main
    pysam.index(outputfile)
  File "/apps/python/2.7.13/lib/python2.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: failed to create index for "A_genome_mapping_sample_1_secondroundAligned.opossum.output.bam": Numerical result out of range\n'
----------------------------------------------------------------------------------------
I am using opossum/0.2

Working on wheat samples with SE reads

Script used : Opossum.py --BamFile=calm.out.bam --SoftClipsExist=True --ProperlyPaired=False --OutFile=A_genome_mapping_sample_1_secondroundAligned.opossum.output.bam

Thanks in advance
Uday**
